### ISSUE TITLE
Bower dependency on angular: "~1.2.14"

### ISSUE THREAD

**Issue by mauricel** [adjohnson916/ng-scope#3]
Thank you for ng-scope, it's really made some of our developers happy.

We have a niggle, however, and that is every time a new version of angular is released, our CI breaks because manual intervention is required to chose between angular 1.2.14 and the latest 1.5.x angular. In our limited testing so far, it seems okay with 1.5

Can you update the bower definition to be less version specific.

**Comment by AndersDJohnson** [comment]
@ml-workshare Thanks. Released as `0.1.3`.
